[slack.Work]
token = "xxxx-xxxx"

[caldav]
url = "https://caldav.example.com"
username = "alice"
password = "secret"
calendar_name = "Work"

[environments.Home]
network = "home-wifi"
emoji = "house_with_garden"
text = "Working @ Home"
until = "17:30"

[environments.Work]
network = "work-wifi"
emoji = "office"
text = "Working in the office"
until = "17:00"